# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: QR-Codes
author: QUADRIGA
logo: assets/logo.jpg
copyright: "2025, QUADRIGA"
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", conda, venv, README.md, LICENSE.md, useful_documentation.md, .github, "**Reviewbogen.md", Checkliste_Finalisierung.md]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache


# Information about where the book exists on the web
repository:
  url: https://github.com/quadriga-dk/qr # Online location of your book
  # path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_repository_button: true
  extra_footer: |
    <p xmlns:cc="http://creativecommons.org/ns#" >This work is licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1" alt=""></a>. For more detailed information please refer to <a href="https://github.com/quadriga-dk/qr/blob/main/LICENSE.md">LICENSE.md</a></p>
  use_multitoc_numbering: false

sphinx:
  config:
    html_show_copyright: false
    html_static_path: ['_static']
    html_css_files:
      - quadriga.css
      - carousel.css
    html_js_files:
      - carousel.js